### PR TITLE
Created footer ui

### PR DESCRIPTION
**Pull request by MukulsinghRajpurohit**
## Title
 Created responsive footer component 

## Proposed Changes

created footer folder and footer component 

## Check List (Check all the applicable boxes)

- [ ] New Feature(s) added
- [ ] My code follows the code style of this project.

## Screenshots (if any)

a1

### CODE REVIEW

**Comment by MukulsinghRajpurohit** [comment]
hi i have made this PR under #35 which is good-first-issue ,if you this this good then plz merge this as this will my first beginner contribution for my learning and GSSOC

**Comment by Abhinavcode13** [comment]
@MukulsinghRajpurohit issue is not assigned to you please do not disobey code of conduct !

**Comment by Abhinavcode13** [comment]
@MukulsinghRajpurohit we basically work on typescript to create the UI component , so this is anyway invalid !

**Comment by MukulsinghRajpurohit** [comment]
@Abhinavcode13 thanks for your feedback but i think you should check #35 issue you see my name assigned by @thekavikumar . 

code of conduct has been followed

second thing i am beginner if some thing get wrong or  invalid you people a there to help  .  so kindly provide specific guidance what is invalid and how to make it valid .

**Comment by Abhinavcode13** [comment]
image
you are not assigned buddy just check ;)

**Pull request closed without merging**
