### PR TITLE
Revert "feat:add template"

### PR DESCRIPTION
**Pull request by thekavikumar**
Reverts thekavikumar/love-simple-ui#55

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
may i know why you reverted it?😅

**Comment by thekavikumar** [comment]
@Ghat0tkach  It didn't work, please check the file you made becoz when I tried creating issue or pull request the template didn't show up

**Comment by Ghat0tkach** [comment]
Oh I apologise for the trouble ,  I'll check it again

**Comment by thekavikumar** [comment]
@Ghat0tkach no problem, take your time! Happy Contributing

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach no problem, take your time! Happy Contributing

please check it again , i do made the necessary changes

**Pull request merged**
