### PR TITLE
Created Test file for button

### LINKED ISSUE #196: Write tests for the components

### PR DESCRIPTION
**Pull request by Killer2OP**
## Title
Test file

## Proposed Changes
File file has been added.

Closes #196 
## Check List (Check all the applicable boxes)

- [ ] Bug(s) fixed
- [X] Enhancement done
- [X] New Feature(s) added
- [ ] Documentation changed
- [X] All new and existing tests passed.
- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by Killer2OP** [comment]
@thekavikumar please review the PR

**Comment by thekavikumar** [comment]
Will review the PR tmw morning! 
Good work!

**Comment by thekavikumar** [comment]
Seems like u didn't run the tests

**Comment by thekavikumar** [comment]
I'm getting a bunch of errors

**Comment by Killer2OP** [comment]
Wait let me look into in then.

**Comment by thekavikumar** [comment]
okay

**Pull request merged**
