### PR TITLE
feat: adding switch component

### PR DESCRIPTION
**Pull request by balaji-sivasakthi**
## Title
Feature request for adding Switch component with props
## Proposed Changes
- added docs for switch
- Switch with props like size, color, bgColor and isChecked
## Check List (Check all the applicable boxes)

- [x] Bug(s) fixed
- [ ] Enhancement done
- [x] New Feature(s) added
- [x] Documentation changed
- [ ] All new and existing tests passed.
- [x] My code follows the code style of this project.

## Additional Information
featured added #179

### CODE REVIEW

**Comment by balaji-sivasakthi** [comment]
@thekavikumar check this one bro

**Comment by thekavikumar** [comment]
please use pnpm and update the commit also there are 14 files that got changed, pls check and do only the required changes

**Comment by balaji-sivasakthi** [comment]
@thekavikumar I removed the package-lock.json file from my commit.

**Review by thekavikumar — APPROVED** [review]

**Comment by thekavikumar** [comment]
image

Can you resolve the error

**Comment by balaji-sivasakthi** [comment]
@thekavikumar Actually, I can't get switch component from **love-simple-ui**. So I did manually copied the dist files to the node_modules/love-simple-ui

**Review by thekavikumar — APPROVED** [review]

**Pull request merged**
