### PR TITLE
Added Alert component with different Type

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Added a new Component Alert it has 4 options Success warning error and default. It has cross icon which when clicked closes the alert and it also vanishes after 6 seconds.  You can define the type and message of alert as its props.

### CODE REVIEW

**Review by thekavikumar — APPROVED** [review]
Will merge pr soon! Great JOB

**Comment by Deepanshu0703** [comment]
Thanks

**Review by kisshan13 — COMMENTED** [review]
for more specific we should add a timeout prop for the component which gives developer a more control on components as per their user interaction.

```ts
export interface AlertProps {
  type?: 'success' | 'warning' | 'error';
  timeout?: number;
  message?: string;
  className?: string;
  onClose?: () => void;
}

export const Alert: FC<AlertProps> = ({ type, message, timeout=6000 ,className = '', onClose }) => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setVisible(false);
    }, timeout);

    return () => clearTimeout(timer);
  }, []);

// rest of the logic here..


};


```

**Comment by Deepanshu0703** [comment]
Thanks for your suggestion i will work on it.

**Review by thekavikumar — APPROVED** [review]
Good JOB!

**Pull request merged**
