### PR TITLE
made the readme more appealing.

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
Hi, I am a GSSOC contributor. I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

### CODE REVIEW

**Review by Cdggtt — CHANGES_REQUESTED** [review]
We have developers in mind! 😊 love-simple-ui is designed to be developer-friendly, providing you with a seamless and enjoyable experience. Our intuitive API and comprehensive documentation make it a breeze to get started and create stunning user interfaces. Whether you're building a simple web app or a complex enterprise application, love-simple-ui has got your back! 💙

Instead of this we changes
We have developer as a top priority! love-simple-ui is designed to be developer-friendly, furnishing you with a  seamless and enjoyable experience. Our intuitive API and comprehensive documentation make it a breeze to get started and create stunning user interfaces. Whether you're fabricating a straightforward web application or an intricate venture application , love-simple-ui has got your back! 💙

**Comment by Ayush-Tibrewal** [comment]
do the change @Cdggtt

**Comment by thekavikumar** [comment]
I'll merge the pr, once I get announcement from GSSoC team

**Comment by Ayush-Tibrewal** [comment]
Thank you @thekavikumar

**Pull request closed without merging**
