### PR TITLE
Create jest.config.ts

### PR DESCRIPTION
**Pull request by Killer2OP**
## Title
Jest.config.ts added

### CODE REVIEW

**Comment by Killer2OP** [comment]
@thekavikumar is this okay or any changes required?

**Comment by thekavikumar** [comment]
Dude try running the test and paste a screenshot of the result here

**Comment by thekavikumar** [comment]
I'm getting a lot of errors now, I just know it happens to me or for everyone

**Comment by Killer2OP** [comment]
> I'm getting a lot of errors now, I just know it happens to me or for everyone

i tried running the test

**Comment by thekavikumar** [comment]
Did that work?

**Comment by Killer2OP** [comment]
> Did that work?

it worked for the normal ones but getting rendering issue in the social ones . wait let me try it by using different method.

**Comment by thekavikumar** [comment]
sure

**Comment by Killer2OP** [comment]
@thekavikumar review my pr and kindly merge

**Pull request closed without merging**
