### PR TITLE
Create Button.test.tsx

### PR DESCRIPTION
**Pull request by Killer2OP**
## Title
Test File

## Proposed Changes
For testing the component file is added.

## Check List (Check all the applicable boxes)

- [ ] Bug(s) fixed
- [ ] Enhancement done
- [X] New Feature(s) added
- [ ] Documentation changed
- [ ] All new and existing tests passed.
- [X] My code follows the code style of this project.

## Additional Information

The dependencies are not added. 
The test file require a few extra dependencies. If you want i can add them.

### CODE REVIEW

**Comment by Killer2OP** [comment]
@thekavikumar Please review and tell about the changes.

**Comment by thekavikumar** [comment]
but what about the dependencies, seems like package.json didn't get updated and no jest.config.ts file?

**Review by thekavikumar — APPROVED** [review]

**Comment by thekavikumar** [comment]
image

**Comment by thekavikumar** [comment]
pls resolve the issue and pr

**Comment by Killer2OP** [comment]
image
the file is running but there is rendering issue.

**Pull request merged**
