### PR TITLE
Added modal

### PR DESCRIPTION
**Pull request by Abhinavcode13**
New UI component resource

## Proposed Changes

Modal Ui component added as a JSX fiile under src folder

## Check List (Check all the applicable boxes)

- [x] Bug(s) fixed
- [x] Enhancement done
- [x] New Feature(s) added
- [x] Documentation changed
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.

closes the issue #95

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Please check @thekavikumar and merge the PR

**Comment by thekavikumar** [comment]
The File is empty

**Comment by Abhinavcode13** [comment]
sorry wait a min

**Review by Abhinavcode13 — COMMENTED** [review]
just once check it

**Comment by Abhinavcode13** [comment]
@thekavikumar check now!!

**Comment by thekavikumar** [comment]
We use tsx in this project not jsx, please make the required changes and develop stories.tsx for the same

**Comment by Abhinavcode13** [comment]
Just check now @thekavikumar added stories.tsx and changed jsx to tsx.

**Comment by Abhinavcode13** [comment]
I think its ready to merge please change the label as gssoc and give a level @thekavikumar , because GSSoC label is invalid and does not count.

**Review by thekavikumar — APPROVED** [review]

**Pull request merged**
