### PR TITLE
create footer ui 

### PR DESCRIPTION
**Pull request by MukulsinghRajpurohit**
### create footer folder to add new different footer ui component .
**till now 3 component are added**

1. Additional footer
2.  link footer
3.  simple footer
A footer
footer folder
L footer
sfooter

###

### CODE REVIEW

**Comment by thekavikumar** [comment]
Bro, make some quality content, this is a very basic design, and I recommend you add some styles

**Review by thekavikumar — CHANGES_REQUESTED** [review]
Add more styles

**Comment by MukulsinghRajpurohit** [comment]
ok

**Comment by MukulsinghRajpurohit** [comment]
should i change this and add new ones or what

**Comment by thekavikumar** [comment]
change it and add styles

**Comment by parthpathakpp1** [comment]
@thekavikumar you can assign me this issue . I can make good improvements in footer section

**Pull request closed without merging**
